### ISSUE TITLE
请问有计划放出论文吗，感谢

### ISSUE THREAD

**Issue by zedzx1uv** [Opdoop/MRAT#1]

**Comment by Opdoop** [comment]
Glad you are interested in our work. Currently, we do not have a preprint link. The paper has been accepted by SIGIR 2021, which will be held on July 11-15. We will add the `dl.acm.org` link as soon as possible~

**Comment by Opdoop** [comment]
😄 Update paper link

**Comment by zedzx1uv** [comment]
Thank you!
